export const GET_CANDIDATES_REQUEST = 'GET_CANDIDATES_REQUEST';
export const GET_CANDIDATES_SUCCESS = 'GET_CANDIDATES_SUCCESS';
export const GET_CANDIDATES_FAIL = 'GET_CANDIDATES_FAIL';

export const GET_ALL_POLLS_REQUEST = 'GET_ALL_POLLS_REQUEST';
export const GET_ALL_POLLS_SUCCESS = 'GET_ALL_POLLS_SUCCESS';
export const GET_ALL_POLLS_FAIL = 'GET_ALL_POLLS_FAIL';
