export const VOTE_REQUEST = 'VOTE_REQUEST';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_FAIL = 'VOTE_FAIL';

export const COUNT_UPDATE_REQUEST = 'COUNT_UPDATE_REQUEST';
export const COUNT_UPDATE_SUCCESS = 'COUNT_UPDATE_SUCCESS';
export const COUNT_UPDATE_FAIL = 'COUNT_UPDATE_FAIL';
